name: apc_proj
channels:
  - nvidia/label/cuda-12.2.0
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - cuda-toolkit=12.2.0
  - pytorch=2.5.1
  - torchvision=0.17.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.2
  - numpy=1.26.4
  - pybind11=2.12.0
  - cmake>=3.20
  - ninja
  - setuptools
  - filelock
  - typing_extensions
  - sympy
  - networkx
  - pillow
  - matplotlib
  - ipython
  - jupyter
  - pytest
  - fsspec
